### ISSUE TITLE
도커파일 주석 달기

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/backend#43]

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/226257194-511e303a-20a8-43de-86a4-213ce62b96ac.png)

도커파일 주석이 추가되었나요? 추가되지 않았다면 `close as not planned`로 닫는 편이 나을 것 같습니다

**Comment by dlwndms0812** [comment]
> ![image](https://user-images.githubusercontent.com/54838975/226257194-511e303a-20a8-43de-86a4-213ce62b96ac.png)
> 
> 도커파일 주석이 추가되었나요? 추가되지 않았다면 `close as not planned`로 닫는 편이 나을 것 같습니다

넵 덕분에 수정했습니다
